export const LOAD_ADMIN="LOAD_ADMIN";
export const LOAD_ATTENDANCE="LOAD_ATTENDANCE";
export const LOAD_STUDENT="LOAD_STUDENT";
export const LOGIN_STUDENT="LOGIN_STUDENT";
export const LOAD_COURSE_CLASS="LOAD_COURSE_CLASS";
export const LOAD_STUDENT_LIST="LOAD_STUDENT_LIST";
